export const Modules = [
  {
    id: 1,
    name: 'Faq',
    icon: 'help-circle',
    color: '#4CAF50',
    count: '50+',
  },
  {
    id: 2,
    name: 'Vendors',
    icon: 'people-circle',
    color: '#2196F3',
    count: '100+',
  },
  {
    id: 3,
    name: 'PriceBooks',
    icon: 'book',
    color: '#FF9800',
    count: '75+',
  },
  {
    id: 4,
    name: 'Quotes',
    icon: 'document-text',
    color: '#9C27B0',
    count: '120+',
  },
  {
    id: 5,
    name: 'PurchaseOrder',
    icon: 'cart',
    color: '#E91E63',
    count: '90+',
  },
  {
    id: 6,
    name: 'SalesOrder',
    icon: 'trending-up',
    color: '#673AB7',
    count: '150+',
  },
  {
    id: 7,
    name: 'Invoice',
    icon: 'receipt',
    color: '#3F51B5',
    count: '200+',
  },
  {
    id: 8,
    name: 'Campaigns',
    icon: 'megaphone',
    color: '#009688',
    count: '45+',
  },
  {
    id: 9,
    name: 'Calendar',
    icon: 'calendar',
    color: '#795548',
    count: '300+',
  },
  {
    id: 10,
    name: 'Leads',
    icon: 'person-add',
    color: '#607D8B',
    count: '180+',
  },
  {
    id: 11,
    name: 'Accounts',
    icon: 'business',
    color: '#FF5722',
    count: '250+',
  },
  {
    id: 12,
    name: 'Contacts',
    icon: 'people',
    color: '#00BCD4',
    count: '400+',
  },
  {
    id: 13,
    name: 'Potentials',
    icon: 'trending-up',
    color: '#8BC34A',
    count: '150+',
  },
  {
    id: 14,
    name: 'Products',
    icon: 'cube',
    color: '#CDDC39',
    count: '320+',
  },
  {
    id: 15,
    name: 'Documents',
    icon: 'document',
    color: '#FFC107',
    count: '280+',
  },
  {
    id: 16,
    name: 'Emails',
    icon: 'mail',
    color: '#03A9F4',
    count: '500+',
  },
  {
    id: 17,
    name: 'HelpDesk',
    icon: 'help-buoy',
    color: '#9E9E9E',
    count: '120+',
  },
  {
    id: 18,
    name: 'Events',
    icon: 'calendar',
    color: '#FF4081',
    count: '180+',
  },
  {
    id: 19,
    name: 'Users',
    icon: 'people',
    color: '#7C4DFF',
    count: '100+',
  },
  {
    id: 20,
    name: 'PBXManager',
    icon: 'call',
    color: '#536DFE',
    count: '60+',
  },
  {
    id: 21,
    name: 'ServiceContracts',
    icon: 'document-text',
    color: '#FF9100',
    count: '90+',
  },
  {
    id: 22,
    name: 'Services',
    icon: 'construct',
    color: '#FF6D00',
    count: '150+',
  },
  {
    id: 23,
    name: 'Assets',
    icon: 'briefcase',
    color: '#2962FF',
    count: '200+',
  },
  {
    id: 24,
    name: 'ModComments',
    icon: 'chatbubbles',
    color: '#00B8D4',
    count: '300+',
  },
  {
    id: 25,
    name: 'ProjectMilestone',
    icon: 'flag',
    color: '#00C853',
    count: '80+',
  },
  {
    id: 26,
    name: 'ProjectTask',
    icon: 'checkbox',
    color: '#64DD17',
    count: '250+',
  },
  {
    id: 27,
    name: 'Project',
    icon: 'folder',
    color: '#304FFE',
    count: '120+',
  },
  {
    id: 28,
    name: 'SMSNotifier',
    icon: 'chatbox',
    color: '#AA00FF',
    count: '100+',
  },
  {
    id: 29,
    name: 'Groups',
    icon: 'people-circle',
    color: '#311B92',
    count: '40+',
  },
  {
    id: 30,
    name: 'Currency',
    icon: 'cash',
    color: '#1B5E20',
    count: '30+',
  },
  {
    id: 31,
    name: 'DocumentFolders',
    icon: 'folder',
    color: '#BF360C',
    count: '60+',
  },
  {
    id: 32,
    name: 'CompanyDetails',
    icon: 'business',
    color: '#263238',
    count: '20+',
  },
  {
    id: 33,
    name: 'LineItem',
    icon: 'list',
    color: '#006064',
    count: '150+',
  },
  {
    id: 34,
    name: 'Tax',
    icon: 'calculator',
    color: '#1A237E',
    count: '40+',
  },
  {
    id: 35,
    name: 'ProductTaxes',
    icon: 'receipt',
    color: '#33691E',
    count: '80+',
  }
]; 